[DEFAULT]

# Browser Settings
browser = chrome
headless = false
maximize_window = true

# Application URL
base_url = https://www.saucedemo.com/

# Waits (in seconds)
implicit_wait = 10
explicit_wait = 20

# Test Credentials
username = standard_user
password = secret_sauce